spring.application.name=companyms
server.port=8082

#PostgreSQL configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/company
spring.datasource.username=faizan
spring.datasource.password=faizan@1234
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Eureka cloud
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
eureka.instance.status-page-url=http://${eureka.instance.hostname}:${server.port}/

#zipkin
management.tracing.sampling.probability=1.0

#Rate Limiter
resilience4j.ratelimiter.instances.company.limitForPeriod=10
resilience4j.ratelimiter.instances.company.limitRefreshPeriod=4s
resilience4j.ratelimiter.instances.company.timeoutDuration=0
resilience4j.ratelimiter.instances.company.eventConsumerBufferSize=10

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
